#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cp $DIR/nginx.conf.template $DIR/nginx.conf
sed -i "s/\\\${HOST_DOMAIN}/$1/g" $DIR/nginx.conf

docker rm pr0clone_webserver > /dev/null
docker run -d --name pr0clone_webserver -v "$DIR/public":/usr/share/nginx/html -v "$DIR/nginx.conf":/etc/nginx/nginx.conf:ro -p $2:80 nginx
